### ISSUE TITLE
''Açık Kaynak'' Anlayışınız

### ISSUE THREAD

**Issue by tunasahinn** [erolerdogan/Kernel-msm3.18#1]
İyi günler Erol hocam, General Mobile'da çalıştığınızı biliyorum (çok açık şekilde belli oluyor). Zamanında Android 10 betası ile yaşadığınız durumdan sonra ''açık kaynağa'' önem verdiğinizi söylemiştiniz. Ancak gönüllü geliştirme yapan kişiler olarak bu durumun bize yansımadığını açık bir şekilde belirtmek isterim. Kernel kaynağı için aylarca yalvarmamız sonucu doğru düzgün bir commit geçmişi bile olmayan, GM 8 harici önemsiz cihazların kernel kaynak kodunu yayınladınız. Tamam commit geçmişinin olmaması bir nebze affedilebilir sonuçta paylaştınız kernel kodu ile Pie ve 10 custom romlar açıldı. Size aylardır GM 9 Pro için kernel kaynağı konusunda yalvarır derecesine geldik. Çevremdeki arkadaşlarım bir sürü arkadaşınıza çeşitli yollardan ulaşmaya çalıştı, ancak sizler kabul edilebilir bir açıklamayı bile uygun görmeyerek mesajlara bile bakmadınız. Tamam kernel kodunu paylaşmayabilirsiniz ancak GM 9 Pro'nun kullandığı **''dokunmatik''** panelinin sürücüsünü sizlerden istedik. Böyle yapmakla geliştiricileri markanıza yapacağı geliştirmelerden soğuttuğunuzu belirtmek isterim. Ayrıca bizlere belirtmiş olduğunuz General Mobile organizasyonunun GM 8 kernelini bile güncellememişsiniz ki biz buradan daha güncelini bulduk. Bizleri göz ardı etmeyip cevap vermeniz umuduyla, iyi günler.

**Comment by kutlay1653** [comment]
gm:tmm

**Comment by barishirece** [comment]
> gm:tmm

neler diosun kutlay ab

**Comment by erolerdogan** [comment]
Merhaba Gençler, az önce Barış'a da yazdım. Aynı cümleleri buraya da yapıştırayım. Ne yazık ki artık General Mobile'da çalışmıyorum :) Keşke sizlere yardımcı olabilsem ihtiyaçlarınızı karşılayabilsem ama elimden pek birşey gelmiyor. Şu kernel repo'larını da siliyim artık :D Başarılarınızın devamını dilerim. Ama size tavsiyem yazılımda sadece kernel'a değilde diğer alanlara da odaklanmanız. Mesela yapay zeka. Kernel kod geliştirmenin Türkiye'de ne yazık çok bir karşılığı bulunmamakta.

Bunun dışında yardımcı olabileceğim bi konu varsa seve seve yardımcı olurum. Kolay gelsin
